<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Identity.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Longevia.Shared.csproj" />
  </ItemGroup>

</Project>
