// Generates a local ES256 keypair for JWT signing and prints it as ready-to-paste
// environment variables. Nothing is written to disk and nothing is logged: the
// private key only ever exists in this process and in the .env you paste it into.
//
//   make jwt-keys
//   make jwt-keys KID=longevia-dev-02
//
// Format follows docs/decisions/001-authn-authz-architecture.md: the values are
// base64 of the PEM on a single line, because an environment variable cannot
// carry newlines. Private key is PKCS#8, public key is SPKI.
//
// Paste PRIVATE into the Identity container only. Diet and Progress get the
// public key and must never receive the private key.

using System.Security.Cryptography;
using System.Text;

var kid = ArgValue("--kid") ?? Environment.GetEnvironmentVariable("KID") ?? "longevia-dev-01";
var issuer = Environment.GetEnvironmentVariable("JWT__ISSUER") ?? "longevia";
var audience = Environment.GetEnvironmentVariable("JWT__AUDIENCE") ?? "longevia-clients";

using var ecdsa = ECDsa.Create(ECCurve.NamedCurves.nistP256);

var privateB64 = ToBase64(ecdsa.ExportPkcs8PrivateKeyPem());
var publicB64 = ToBase64(ecdsa.ExportSubjectPublicKeyInfoPem());

// Fail loudly here rather than handing out an unusable value: this is the same
// check the app will do at startup via ValidateOnStart().
if (ImportFrom(privateB64) is null || ImportFrom(publicB64) is null)
{
    Console.Error.WriteLine("Generated key failed the round-trip check.");
    return 1;
}

Console.WriteLine($"# Generated by `make jwt-keys` (kid={kid}).");
Console.WriteLine("# Copy these into .env. Keep the private key on the Identity service only.");
Console.WriteLine();
Console.WriteLine($"JWT__KEY_ID={kid}");
Console.WriteLine($"JWT__SIGNING_PRIVATE_KEY={privateB64}");
Console.WriteLine($"JWT__SIGNING_PUBLIC_KEY={publicB64}");
Console.WriteLine();
Console.WriteLine($"# Existing JWT__ISSUER={issuer} and JWT__AUDIENCE={audience} stay as they are.");
Console.WriteLine();
Console.WriteLine("# Rotating an already-deployed key? Keep the old public key alongside the new");
Console.WriteLine("# one until every token signed with it has expired, then clear these:");
Console.WriteLine("#");
Console.WriteLine("# JWT__PREVIOUS_KEY_ID=<old kid>");
Console.WriteLine("# JWT__PREVIOUS_PUBLIC_KEY=<old public key>");

return 0;

static string ToBase64(string pem) => Convert.ToBase64String(Encoding.UTF8.GetBytes(pem));

static ECDsa? ImportFrom(string base64Pem)
{
    try
    {
        var ecdsa = ECDsa.Create();
        ecdsa.ImportFromPem(Encoding.UTF8.GetString(Convert.FromBase64String(base64Pem)));
        return ecdsa;
    }
    catch (Exception)
    {
        return null;
    }
}

static string? ArgValue(string name)
{
    var args = Environment.GetCommandLineArgs();
    for (var i = 0; i < args.Length - 1; i++)
    {
        if (args[i] == name)
        {
            return args[i + 1];
        }
    }

    return null;
}